version: '3.3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  rabbitmq-consumer:
    container_name: rabbitmq-consumer
    build:
      context: ./rabbitmq-consumer
      dockerfile: Dockerfile
    volumes:
      - /tmp:/tmp
    restart: on-failure
  
  uf:
    container_name: uf
    build:
      context: ./uf
      dockerfile: Dockerfile
      args:
        - RELEASE_URL=7.3.6/linux/splunkforwarder-7.3.6-47d8552a4d84-Linux-x86_64.tgz