# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "file", before: :all, source: "./forwarder-compose.yml",
                      destination: "/home/vagrant/image/docker-compose.yml"
  config.vm.provision "file", before: :all, source: "./rabbitmq-consumer",
                      destination: "/home/vagrant/image/rabbitmq-consumer"
  config.vm.provision "file", before: :all, source: "./uf",
                      destination: "/home/vagrant/image/uf"
  config.vm.provision "file", before: :all, source: "../common/files/indexers.txt",
                      destination: "/tmp/indexers.txt"
  config.vm.provision "file", before: :all, source: universalforwarder_path,
                      destination: "/home/vagrant/image/uf/universalforwarder.tgz"


  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end


  config.vm.provision "outputs.conf", before: :all, type: "shell", path: "../common/configs/outputs.py", args: "/home/vagrant/image/uf/outputs.conf"
  config.vm.provision "set_date", before: :all, type: "shell", inline: <<-SHELL
    timedatectl set-timezone Europe/Madrid
  SHELL
  config.vm.provision "install_docker", before: :all, path: "../common/scripts/install_docker.sh", type: "shell"
  config.vm.provision :docker_compose, after: :all, yml: "/home/vagrant/image/docker-compose.yml", run: "always"


  File.open('../common/files/forwarders.txt') do |f|
    f.each_line.with_index do |server, index|
      server = server = server.gsub("\n","").gsub("\r","").gsub(" ","").gsub(":", "")
      num_idx = index + 1

      config.vm.define "uf#{num_idx}" do |uf|
        uf.vm.network :private_network, ip: "#{server}"
        uf.vm.provider :virtualbox do |vb|
          vb.name = "splunk-uf-#{num_idx}"
        end

        uf.vm.provision "server.conf", type: "shell", path: "../common/configs/server.py", args: "splunk_uf_#{num_idx} /home/vagrant/image/uf/server.conf"
      end
    end
  end
end