# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.provision "file", source: "./Dockerfile", 
                        destination: "/tmp/Dockerfile"
    config.vm.provision "file", source: "../common/files/shcluster_members.txt", 
                        destination: "/tmp/shcluster_members.txt"

    config.vm.network :private_network, ip: "192.168.33.4"

    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
        v.name = "load-balancer"
    end

    config.vm.provision "basic", before: :all, type: "shell", inline: <<-SHELL
        timedatectl set-timezone Europe/Madrid
        apt-get update
        apt-get install -y python3-pip
        pip3 install python-nginx
    SHELL

    config.vm.provision "install_docker", before: :all, path: "../common/scripts/install_docker.sh", type: "shell"
    config.vm.provision "nginx.conf", type: "shell", path: "./nginx.py"

    config.vm.provision "docker" do |d|
        d.build_image "/tmp", args: '-t load-balancer'
        d.run "load-balancer", image: "load-balancer", args: "-p 80:80"
    end
end